/*
 * boot0_head.c
 *
 * Copyright (C) 2013 Qiang Yu <yuq825@gmail.com>
 *
 * a simple tool to generate bootable image for sunxi platform.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License as
 * published by the Free Software Foundation; either version 2 of
 * the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.	 See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston,
 * MA 02111-1307 USA
 */

typedef int s32;
typedef unsigned int u32;
typedef unsigned char u8;

typedef struct _boot_file_head
{
	u32  jump_instruction;   // one intruction jumping to real code
	u8   magic[8];           // ="eGON.BT0" or "eGON.BT1",  not C-style string.
	u32  check_sum;          // generated by PC
	u32  length;             // generated by PC
	u32  pub_head_size;      // the size of boot_file_head_t
	u8   pub_head_vsn[4];    // the version of boot_file_head_t
	u8   file_head_vsn[4];   // the version of boot0_file_head_t or boot1_file_head_t
	u8   Boot_vsn[4];        // Boot version
	u8   eGON_vsn[4];        // eGON version
	u8   platform[8];        // platform information
} boot_file_head_t;

typedef struct _boot_dram_para_t {
    u32 dram_baseaddr;
    u32 dram_clk;
    u32 dram_type;
    u32 dram_rank_num;
    u32 dram_chip_density;
    u32 dram_io_width;
    u32 dram_bus_width;
    u32 dram_cas;
    u32 dram_zq;
    u32 dram_odt_en;
    u32 dram_size;
    u32 dram_tpr0;
    u32 dram_tpr1;
    u32 dram_tpr2;
    u32 dram_tpr3;
    u32 dram_tpr4;
    u32 dram_tpr5;
    u32 dram_emr1;
    u32 dram_emr2;
    u32 dram_emr3;
} boot_dram_para_t;

typedef struct _normal_gpio_cfg {
    u8 port;
    u8 port_num;
    u8 mul_sel;
    u8 pull;
    u8 drv_level;
    u8 data;
    u8 reserved[2];
} normal_gpio_cfg;

typedef struct _boot0_private_head_t {
    u32 prvt_head_size;
    char prvt_head_vsn[4];
    boot_dram_para_t dram_para;
    s32 uart_port;
    normal_gpio_cfg uart_ctrl[2];
    s32 enable_jtag;
    normal_gpio_cfg jtag_gpio[5];
    normal_gpio_cfg storage_gpio[32];
    u8 storage_data[256];
} boot0_private_head_t;

typedef struct _boot0_file_head_t {
    boot_file_head_t boot_head;
    boot0_private_head_t prvt_head;
} boot0_file_head_t;

#define BOOT0_MAGIC                     "eGON.BT0"
#define STAMP_VALUE                     0x5F0A6C39
#ifdef CONFIG_SUNXI_NAND_SPL
#define BOOT0_ALIGN_SIZE                0x2000
#else
#define BOOT0_ALIGN_SIZE                0x0400
#endif
#define BOOT_PUB_HEAD_VERSION           "1100"
#define BOOT0_FILE_HEAD_VERSION         "1230"
#define BOOT0_VERSION                   "1230"
#define EGON_VERSION                    "1100"
#define BOOT0_PRVT_HEAD_VERSION         "1230"

const boot0_file_head_t boot0_head __attribute__((section(".text"))) = {
	{
		(0xEA000000 | (((sizeof(boot0_file_head_t) + sizeof(int) - 1) / sizeof(int) - 2) & 0x00FFFFFF)),
		BOOT0_MAGIC,
		STAMP_VALUE,
		BOOT0_ALIGN_SIZE,
		sizeof(boot_file_head_t),
		BOOT_PUB_HEAD_VERSION,
		BOOT0_FILE_HEAD_VERSION,
		BOOT0_VERSION,
		EGON_VERSION,
		{ 0, '1', '.', '5', '.', '0', 0, 0 },
	},

	{
		sizeof( boot0_private_head_t ),
		BOOT0_PRVT_HEAD_VERSION,
		{ 
			0x40000000,
			360,
			3,
			1,
			2048,
			16,
			32,
			6,
			0x7b,
			0,
			512,
			0x30926692,
			0x1090,
			0x1a0c8,
			0x0,
			0x0,
			0x0,
			0x0,
			0x0,
			0x0
		},
		0,
		{
			{ 2, 22, 2, 1, 1, 0, 0, 0},
			{ 2, 23, 2, 1, 1, 0, 0, 0}
		},
		0,
		{ 0 },
		{ 0 },
		{ 0 }
	}
};
